name: firebase_core_tizen
description: Tizen implementation of the firebase_core plugin.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/firebase_core
version: 0.2.0

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  firebase_core: ^4.2.0
  firebase_core_platform_interface: ^6.0.2
  firebase_dart: ^1.6.2
  flutter:
    sdk: flutter
  path_provider_tizen: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      tizen:
        dartPluginClass: FirebaseCore

false_secrets:
  - /example/lib/main.dart
