name: cloud_functions_tizen_example
description: Demonstrates how to use the cloud_functions_tizen plugin.

publish_to: 'none'

environment:
  flutter: '>=3.27.0'
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  cloud_functions: ^6.2.0
  cloud_functions_tizen:
    path: ..
  firebase_core: ^4.7.0
  firebase_core_tizen:
    path: ../../firebase_core
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  integration_test_tizen: ^2.0.1

flutter:
  uses-material-design: true
