name: firebase_storage_tizen
description: Tizen implementation of the firebase_storage plugin.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/firebase_storage
version: 0.2.0

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  firebase_core: ^4.7.0
  firebase_core_tizen: ^0.2.0
  firebase_dart: ^1.6.2
  firebase_storage: ^13.3.0
  firebase_storage_platform_interface: ^5.2.20
  flutter:
    sdk: flutter

dependency_overrides:
  firebase_core_tizen:
    path: ../firebase_core

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: firebase_storage
    platforms:
      tizen:
        dartPluginClass: FirebaseStorageTizen

false_secrets:
  - /example/lib/main.dart
