name: analyze

on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - name: Install plugin tool dependencies
        run: dart pub get
        working-directory: tools
      - name: Dart analyze
        run: ./tools/tools_runner.sh analyze --custom-analysis=$(ls packages | tr '\n' ',')
      - name: Dart format
        run: ./tools/tools_runner.sh format --fail-on-change --no-clang-format
